import type { Config } from "tailwindcss"

const config: Config = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                surface: "#faf9f4",
                "surface-dim": "#dbdad5",
                "surface-bright": "#faf9f4",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f5f4ef",
                "surface-container": "#efeee9",
                "surface-container-high": "#e9e8e3",
                "surface-container-highest": "#e3e3de",
                "on-surface": "#1b1c19",
                "on-surface-variant": "#45464e",
                "inverse-surface": "#30312e",
                "inverse-on-surface": "#f2f1ec",
                outline: "#75777f",
                "outline-variant": "#c5c6cf",
                "surface-tint": "#505e80",
                primary: {
                    DEFAULT: "#00061a",
                    foreground: "#ffffff",
                },
                "on-primary": "#ffffff",
                "primary-container": "#0f1e3d",
                "on-primary-container": "#7886ab",
                "inverse-primary": "#b8c6ee",
                secondary: {
                    DEFAULT: "#5f5e5e",
                    foreground: "#ffffff",
                },
                "on-secondary": "#ffffff",
                "secondary-container": "#e2dfde",
                "on-secondary-container": "#636262",
                tertiary: "#000714",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#0f2033",
                "on-tertiary-container": "#7888a0",
                error: {
                    DEFAULT: "#ba1a1a",
                    foreground: "#ffffff",
                },
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                success: "#3f6b3f",
                "on-success": "#ffffff",
                background: "#faf9f4",
                "on-background": "#1b1c19",
                "surface-variant": "#e3e3de",
                foreground: "#1b1c19",
                card: {
                    DEFAULT: "#ffffff",
                    foreground: "#1b1c19",
                },
                popover: {
                    DEFAULT: "#ffffff",
                    foreground: "#1b1c19",
                },
                muted: {
                    DEFAULT: "#efeee9",
                    foreground: "#45464e",
                },
                accent: {
                    DEFAULT: "#efeee9",
                    foreground: "#1b1c19",
                },
                destructive: {
                    DEFAULT: "#ba1a1a",
                    foreground: "#ffffff",
                },
                border: "#c5c6cf",
                input: "#c5c6cf",
                ring: "#00061a",
            },
            fontFamily: {
                serif: ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
                sans: ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
                "headline-display": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
                "headline-lg": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
                "headline-md": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
                "body-lg": ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
                "body-md": ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
                "label-caps": ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
                "ui-button": ["var(--font-hanken)", "Hanken Grotesk", "system-ui", "sans-serif"],
            },
            fontSize: {
                "headline-display": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
                "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
                "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "600" }],
                "ui-button": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
            },
            spacing: {
                "page-gutter": "80px",
                "section-gap": "120px",
                "section-gap-sm": "64px",
                "container-max": "1280px",
                gutter: "32px",
                "stack-sm": "8px",
                "stack-md": "16px",
                "stack-lg": "32px",
                "stack-xl": "64px",
            },
            maxWidth: {
                "container-max": "1280px",
                prose: "65ch",
            },
            borderRadius: {
                none: "0",
                sm: "0.125rem",
                DEFAULT: "0.25rem",
                md: "0.375rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1rem",
                full: "9999px",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
                "fade-in": {
                    from: { opacity: "0" },
                    to: { opacity: "1" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "fade-in": "fade-in 200ms ease-out",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
}

export default config
